
supported_langs = [
  {
		"flag": "",
		"label": "English",
		"code": "en",
		"country": "United Kingdom",
	},
	{
		"flag": "",
		"label": "Spanish",
		"code": "es",
		"country": "Spain",
	},
  {
		"flag": "",
		"label": "French",
		"code": "fr",
		"country": "France",
	},
	{
		"flag": "",
		"label": "German",
		"code": "de",
		"country": "Germany",
	},
	{
		"flag": "",
		"label": "Hindi",
		"code": "hi",
		"country": "India",
	},
	{
		"flag": "",
		"label": "Russian",
		"code": "ru",
		"country": "Russia",
	},
	{
		"flag": "",
		"label": "Portuguese",
		"code": "pt",
		"country": "Portugal",
	},
	{
		"flag": "",
		"label": "Japanese",
		"code": "ja",
		"country": "Japan",
	},
	{
		"flag": "",
		"label": "Italian",
		"code": "it",
		"country": "Italy",
	},
	{
		"flag": "",
		"label": "Dutch",
		"code": "nl",
		"country": "Netherlands",
	}
]

supported_output_langs = [
    {"id": 1, "code": "EN-US", "name": "English", "country": "American", "short_name": "en-us", "language": "english", "country": "united states"},
    {"id": 35, "code": "EN-GB", "name": "English", "country": "British", "short_name": "en-gb", "language": "english", "country": "united kingdom"},
    {"id": 4, "code": "AR", "name": "Arabic", "short_name": "ar-ae", "language": "arabic", "country": "united arab emirates"},
    # {"id": 5, "code": "AR", "name": "Arabic", "short_name": "ar-bh", "language": "arabic", "country": "bahrain"},
    # {"id": 6, "code": "AR", "name": "Arabic", "short_name": "ar-dz", "language": "arabic", "country": "algeria"},
    # {"id": 7, "code": "AR", "name": "Arabic", "short_name": "ar-eg", "language": "arabic", "country": "egypt"},
    # {"id": 8, "code": "AR", "name": "Arabic", "short_name": "ar-iq", "language": "arabic", "country": "iraq"},
    # {"id": 9, "code": "AR", "name": "Arabic", "short_name": "ar-jo", "language": "arabic", "country": "jordan"},
    # {"id": 10, "code": "AR", "name": "Arabic", "short_name": "ar-kw", "language": "arabic", "country": "kuwait"},
    # {"id": 11, "code": "AR", "name": "Arabic", "short_name": "ar-lb", "language": "arabic", "country": "lebanon"},
    # {"id": 12, "code": "AR", "name": "Arabic", "short_name": "ar-ly", "language": "arabic", "country": "libya"},
    # {"id": 13, "code": "AR", "name": "Arabic", "short_name": "ar-ma", "language": "arabic", "country": "morocco"},
    # {"id": 14, "code": "AR", "name": "Arabic", "short_name": "ar-om", "language": "arabic", "country": "oman"},
    # {"id": 15, "code": "AR", "name": "Arabic", "short_name": "ar-qa", "language": "arabic", "country": "qatar"},
    # {"id": 16, "code": "AR", "name": "Arabic", "short_name": "ar-sa", "language": "arabic", "country": "saudi arabia"},
    # {"id": 17, "code": "AR", "name": "Arabic", "short_name": "ar-sy", "language": "arabic", "country": "syria"},
    # {"id": 18, "code": "AR", "name": "Arabic", "short_name": "ar-tn", "language": "arabic", "country": "tunisia"},
    # {"id": 19, "code": "AR", "name": "Arabic", "short_name": "ar-ye", "language": "arabic", "country": "yemen"},
    {"id": 21, "code": "BG", "name": "Bulgarian", "short_name": "bg-bg", "language": "bulgarian", "country": "bulgaria"},
    {"id": 26, "code": "CS", "name": "Czech", "short_name": "cs-cz", "language": "czech", "country": "czechia"},
    {"id": 28, "code": "DA", "name": "Danish", "short_name": "da-dk", "language": "danish", "country": "denmark"},
    {"id": 29, "code": "DE", "name": "German", "short_name": "de-at", "language": "german", "country": "austria"},
    {"id": 30, "code": "DE", "name": "German", "short_name": "de-ch", "language": "german", "country": "switzerland"},
    {"id": 31, "code": "DE", "name": "German", "short_name": "de-de", "language": "german", "country": "germany"},
    {"id": 32, "code": "EL", "name": "Greek", "short_name": "el-gr", "language": "greek", "country": "greece"},
    {"id": 54, "code": "ES", "name": "Spanish", "short_name": "es-es", "language": "spanish", "country": "spain"},
    {"id": 46, "code": "ES", "name": "Spanish", "short_name": "es-ar", "language": "spanish", "country": "argentina"},
    # {"id": 47, "code": "ES", "name": "Spanish", "short_name": "es-bo", "language": "spanish", "country": "bolivia"},
    # {"id": 48, "code": "ES", "name": "Spanish", "short_name": "es-cl", "language": "spanish", "country": "chile"},
    # {"id": 49, "code": "ES", "name": "Spanish", "short_name": "es-co", "language": "spanish", "country": "colombia"},
    # {"id": 50, "code": "ES", "name": "Spanish", "short_name": "es-cr", "language": "spanish", "country": "costa rica"},
    # {"id": 51, "code": "ES", "name": "Spanish", "short_name": "es-cu", "language": "spanish", "country": "cuba"},
    # {"id": 52, "code": "ES", "name": "Spanish", "short_name": "es-do", "language": "spanish", "country": "dominican republic"},
    # {"id": 53, "code": "ES", "name": "Spanish", "short_name": "es-ec", "language": "spanish", "country": "ecuador"},
    # {"id": 55, "code": "ES", "name": "Spanish", "short_name": "es-gq", "language": "spanish", "country": "equatorial guinea"},
    # {"id": 56, "code": "ES", "name": "Spanish", "short_name": "es-gt", "language": "spanish", "country": "guatemala"},
    # {"id": 57, "code": "ES", "name": "Spanish", "short_name": "es-hn", "language": "spanish", "country": "honduras"},
    # {"id": 58, "code": "ES", "name": "Spanish", "short_name": "es-mx", "language": "spanish", "country": "mexico"},
    # {"id": 59, "code": "ES", "name": "Spanish", "short_name": "es-ni", "language": "spanish", "country": "nicaragua"},
    # {"id": 60, "code": "ES", "name": "Spanish", "short_name": "es-pa", "language": "spanish", "country": "panama"},
    # {"id": 61, "code": "ES", "name": "Spanish", "short_name": "es-pe", "language": "spanish", "country": "peru"},
    # {"id": 62, "code": "ES", "name": "Spanish", "short_name": "es-pr", "language": "spanish", "country": "puerto rico"},
    # {"id": 63, "code": "ES", "name": "Spanish", "short_name": "es-py", "language": "spanish", "country": "paraguay"},
    # {"id": 64, "code": "ES", "name": "Spanish", "short_name": "es-sv", "language": "spanish", "country": "el salvador"},
    # {"id": 65, "code": "ES", "name": "Spanish", "short_name": "es-us", "language": "spanish", "country": "united states"},
    # {"id": 66, "code": "ES", "name": "Spanish", "short_name": "es-uy", "language": "spanish", "country": "uruguay"},
    # {"id": 67, "code": "ES", "name": "Spanish", "short_name": "es-ve", "language": "spanish", "country": "venezuela"},
    {"id": 68, "code": "ET", "name": "Estonian", "short_name": "et-ee", "language": "estonian", "country": "estonia"},
    {"id": 71, "code": "FI", "name": "Finnish", "short_name": "fi-fi", "language": "finnish", "country": "finland"},
    # {"id": 73, "code": "FR", "name": "French", "short_name": "fr-be", "language": "french", "country": "belgium"},
    # {"id": 74, "code": "FR", "name": "French", "short_name": "fr-ca", "language": "french", "country": "canada"},
    # {"id": 75, "code": "FR", "name": "French", "short_name": "fr-ch", "language": "french", "country": "switzerland"},
    {"id": 76, "code": "FR", "name": "French", "short_name": "fr-fr", "language": "french", "country": "france"},
    {"id": 83, "code": "HU", "name": "Hungarian", "short_name": "hu-hu", "language": "hungarian", "country": "hungary"},
    {"id": 85, "code": "ID", "name": "Indonesian", "short_name": "id-id", "language": "indonesian", "country": "indonesia"},
    {"id": 87, "code": "IT", "name": "Italian", "short_name": "it-it", "language": "italian", "country": "italy"},
    {"id": 88, "code": "JA", "name": "Japanese", "short_name": "ja-jp", "language": "japanese", "country": "japan"},
    {"id": 94, "code": "KO", "name": "Korean", "short_name": "ko-kr", "language": "korean", "country": "korea"},
    {"id": 96, "code": "LT", "name": "Lithuanian", "short_name": "lt-lt", "language": "lithuanian", "country": "lithuania"},
    {"id": 97, "code": "LV", "name": "Latvian", "short_name": "lv-lv", "language": "latvian", "country": "latvia"},
    {"id": 105, "code": "NB", "name": "Norwegian Bokmål", "short_name": "nb-no", "language": "norwegian", "country": "bokmål, norway"},
    {"id": 107, "code": "NL", "name": "Dutch", "short_name": "nl-be", "language": "dutch", "country": "belgium"},
    {"id": 108, "code": "NL", "name": "Dutch", "short_name": "nl-nl", "language": "dutch", "country": "netherlands"},
    {"id": 109, "code": "PL", "name": "Polish", "short_name": "pl-pl", "language": "polish", "country": "poland"},
    {"id": 111, "code": "PT-BR", "name": "Portuguese", "country": "Brazilian", "short_name": "pt-br", "language": "portuguese", "country": "brazil"},
    {"id": 112, "code": "PT-PT", "name": "Portuguese", "country": "all Portuguese variants excluding Brazilian Portuguese", "short_name": "pt-pt", "language": "portuguese", "country": "portugal"},
    {"id": 113, "code": "RO", "name": "Romanian", "short_name": "ro-ro", "language": "romanian", "country": "romania"},
    {"id": 114, "code": "RU", "name": "Russian", "short_name": "ru-ru", "language": "russian", "country": "russia"},
    {"id": 116, "code": "SK", "name": "Slovak", "short_name": "sk-sk", "language": "slovak", "country": "slovakia"},
    {"id": 117, "code": "SL", "name": "Slovenian", "short_name": "sl-si", "language": "slovenian", "country": "slovenia"},
    {"id": 122, "code": "SV", "name": "Swedish", "short_name": "sv-se", "language": "swedish", "country": "sweden"},
    {"id": 131, "code": "TR", "name": "Turkish", "short_name": "tr-tr", "language": "turkish", "country": "turkey"},
    {"id": 132, "code": "UK", "name": "Ukrainian", "short_name": "uk-ua", "language": "ukrainian", "country": "ukraine"},
    {"id": 139, "code": "ZH-HANS", "name": "Chinese", "country": "simplified", "short_name": "zh-cn", "language": "chinese", "country": "mandarin, simplified"},
    {"id": 146, "code": "ZH-HANT", "name": "Chinese", "country": "traditional", "short_name": "zh-tw", "language": "chinese", "country": "taiwanese mandarin, traditional"}
]

